/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '01.Map': typeof import('./src/components/01.Map.vue')['default']
    '02.Picture': typeof import('./src/components/02.Picture.vue')['default']
    '03.Graricule': typeof import('./src/components/03.Graricule.vue')['default']
    '04.HeatmapLayer': typeof import('./src/components/04.HeatmapLayer.vue')['default']
    '05.WebGLPointsLayer': typeof import('./src/components/05.WebGLPointsLayer.vue')['default']
    '06.shift': typeof import('./src/components/06.shift.vue')['default']
    '07.MousePosition': typeof import('./src/components/07.MousePosition.vue')['default']
    '08.OverviewMap': typeof import('./src/components/08.OverviewMap.vue')['default']
    '09.Overlaypopup1': typeof import('./src/components/09.Overlaypopup1.vue')['default']
    '10.demo1': typeof import('./src/components/10.demo1.vue')['default']
    '11.PictureDemo': typeof import('./src/components/11.PictureDemo.vue')['default']
    '12.Text': typeof import('./src/components/12.Text.vue')['default']
    '13.vue切片图层TileLayer切换地图底图，图层叠加效果': typeof import('./src/components/13.vue切片图层TileLayer切换地图底图，图层叠加效果.vue')['default']
    '14.裁剪base': typeof import('./src/components/14.裁剪base.vue')['default']
    '15.裁剪模糊版本': typeof import('./src/components/15.裁剪模糊版本.vue')['default']
    '16.裁剪perfect': typeof import('./src/components/16.裁剪perfect.vue')['default']
    '17.图片90度旋转': typeof import('./src/components/17.图片90度旋转.vue')['default']
    '18.遮罩base': typeof import('./src/components/18.遮罩base.vue')['default']
    '19.遮罩base_无循环': typeof import('./src/components/19.遮罩base_无循环.vue')['default']
    '20.滚轮放大缩小功能': typeof import('./src/components/20.滚轮放大缩小功能.vue')['default']
    '23.聚合demo': typeof import('./src/components/23.聚合demo.vue')['default']
    '24.定位demo': typeof import('./src/components/24.定位demo.vue')['default']
    '25.绘图demo': typeof import('./src/components/25.绘图demo.vue')['default']
    '26.简单绘图demo': typeof import('./src/components/26.简单绘图demo.vue')['default']
    '27.FLV.js处理视频': typeof import('./src/components/27.FLV.js处理视频.vue')['default']
    '28.canvasDemo': typeof import('./src/components/28.canvasDemo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
